[project]
name = "sentiment-analysis"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "nicegui>=2.19.0",
    "notebook>=7.4.3",
    "streamlit>=1.45.1",
]
